/* include/urbix.h — Auto-generated by cbindgen. Do not edit manually;
 * regenerate with `cargo build`.
 *
 * See Urbix_Project.md §2.3 (wire format) and §2.4 (FFI surface). */

#ifndef URBIX_H
#define URBIX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Interior layout blueprint selection (see `layout.rs` / `InteriorContext`).
 */
#define LAYOUT_PICK 40

/**
 * Interior per-floor layout variation (see `layout.rs`).
 */
#define LAYOUT_FLOOR 41

/**
 * Interior room-kind selection (see `layout.rs`).
 */
#define LAYOUT_ROOM 42

/**
 * Interior room size (width/depth) draw (see `layout.rs`).
 */
#define LAYOUT_ROOM_SIZE 43

/**
 * Interior door placement (see `layout.rs`).
 */
#define LAYOUT_DOOR 44

/**
 * Interior furniture slot density (see `layout.rs`).
 */
#define LAYOUT_FURNITURE 45

/**
 * Maximum room templates a single zone [`Blueprint`] can hold.
 *
 * The blueprint is a fixed-size `#[repr(C)]` record so it can live inside
 * `WorldConfig` and cross the FFI; `room_count` marks how many of the
 * `MAX_BLUEPRINT_ROOMS` slots are live. 8 comfortably fits all five zones'
 * defaults (largest is Downtown at 4).
 */
#define MAX_BLUEPRINT_ROOMS 8

/**
 * Number of `InteriorLayout` floors assumed for worlds units per storey when
 * deriving `floor_count` from building height. Kept as a compile-time default;
 * `WorldConfig.interior_floor_height` overrides it at runtime.
 */
#define DEFAULT_FLOOR_HEIGHT 4.0

/**
 * Number of `InteriorLayout` floors cap when deriving `floor_count` from
 * building height. `WorldConfig.interior_max_floors` overrides it at runtime.
 */
#define DEFAULT_MAX_FLOORS 64

/**
 * Room adjacency/program tag bits for [`BlueprintRoom::tags`].
 *
 * Tags steer placement without the engine knowing room semantics: `WET`
 * rooms snap to plumbing shafts, `QUIET` rooms avoid street edges and the
 * core, `PUBLIC` rooms prefer the entrance half, `STREET` rooms prefer the
 * wall ring facing outside.
 */
#define TAG_WET (1 << 0)

/**
 * Quiet room tag bit (see [`TAG_WET`]).
 */
#define TAG_QUIET (1 << 1)

/**
 * Public room tag bit (see [`TAG_WET`]).
 */
#define TAG_PUBLIC (1 << 2)

/**
 * Street-facing room tag bit (see [`TAG_WET`]).
 */
#define TAG_STREET (1 << 3)

/**
 * No furniture (bare tile).
 */
#define FURN_NONE 0

/**
 * Bed (bedrooms).
 */
#define FURN_BED 1

/**
 * Table (living, meeting, work bays).
 */
#define FURN_TABLE 2

/**
 * Counter run (kitchens, retail, washrooms).
 */
#define FURN_COUNTER 3

/**
 * Desk (offices, lobbies, receptions).
 */
#define FURN_DESK 4

/**
 * Shelf (stockrooms, living rooms, utility).
 */
#define FURN_SHELF 5

/**
 * Bath fixture (bathrooms).
 */
#define FURN_BATH 6

/**
 * The number of distinct zone types.
 */
#define ZONE_COUNT 5

/**
 * Opaque handle to a [`WorldEngine`], owned by the caller.
 *
 * Never dereference from foreign code; pass it back to the FFI functions.
 * Deliberately not `#[repr(C)]`: it is a zero-sized opaque marker whose layout
 * is irrelevant, and cbindgen emits an opaque forward-declared typedef for it.
 */
typedef struct UrbixEngine UrbixEngine;

/**
 * An owned chunk's packed bytes handed to foreign code.
 *
 * `data` points at `len` bytes: a [`crate::data::ChunkHeader`] followed by
 * `cell_count` [`crate::data::Cell`] records with no padding. The caller owns
 * this buffer and must free it with [`urbix_chunk_free`].
 */
typedef struct UrbixChunkBuffer {
    /**
     * Start of the wire buffer (header + cells).
     */
    uint8_t *data;
    /**
     * Total byte length (`sizeof(header) + cell_count * sizeof(cell)`).
     */
    uint64_t len;
} UrbixChunkBuffer;

/**
 * A generated building interior handed to foreign code.
 *
 * `data` points at `len` bytes laid out as one payload chunk per floor, in
 * storey order:
 *
 * ```text
 * floor i (i in 0..floor_count):
 *   tiles[footprint_w * footprint_d]   // one Tile byte each, row-major
 *   kinds[footprint_w * footprint_d]   // room-kind tag byte each, 0 = not room
 *   furn[footprint_w * footprint_d]    // furniture code byte each, 0 = bare (M15)
 * ```
 *
 * Every floor shares the same `footprint_w × footprint_d` grid, so `len` is
 * exactly `floor_count * 3 * footprint_w * footprint_d`. The furniture layer
 * is appended (never interleaved): readers slicing the first two thirds
 * keep working unchanged. `Tile` bytes are the
 * [`crate::layout::Tile`] enum values (0 = void, 1 = wall, 2 = door, 3 = core,
 * 4 = corridor, 5 = room); furniture bytes are the `FURN_*` codes
 * (`crate::layout`, 0 = bare, set only where the tile is `Room`). The caller
 * owns this payload and must release it with [`urbix_interior_free`]. An
 * unbuilt cell (height ≤ 0) or null engine yields a zeroed header with
 * `data == null` and `len == 0`.
 */
typedef struct UrbixInterior {
    /**
     * Stable interior key (the built cell's deterministic key).
     */
    uint64_t interior_id;
    /**
     * World seed used during generation.
     */
    uint64_t seed;
    /**
     * Dominant [`crate::zones::ZoneType`] index (0–4).
     */
    uint8_t zone;
    /**
     * [`crate::layout::DoorSide`] index (0 = west, 1 = east, 2 = north, 3 = south).
     */
    uint8_t door_side;
    /**
     * Shared floor-grid width in tiles.
     */
    uint8_t footprint_w;
    /**
     * Shared floor-grid depth in tiles.
     */
    uint8_t footprint_d;
    /**
     * Number of storeys (`len` = `floor_count * 3 * footprint_w * footprint_d`).
     */
    uint16_t floor_count;
    /**
     * Total payload byte length; 0 when unbuilt.
     */
    uint64_t len;
    /**
     * Start of the payload (see struct docs); null when unbuilt.
     */
    uint8_t *data;
} UrbixInterior;

/**
 * One enumerated room: rect plus kind, apartment, and area.
 *
 * Produced by [`urbix_generate_interior_rooms`] from the same finished
 * floors [`urbix_generate_interior`] ships, so grids and records always
 * agree. `unit` indexes the floor's apartment list (`255` = outside every
 * unit); `kind` is the opaque blueprint room tag; `area` counts tiles.
 */
typedef struct UrbixRoom {
    /**
     * Storey index within the interior.
     */
    uint8_t floor;
    /**
     * Left edge in grid cells.
     */
    uint8_t x;
    /**
     * Top edge in grid cells.
     */
    uint8_t z;
    /**
     * Width in cells.
     */
    uint8_t w;
    /**
     * Depth in cells.
     */
    uint8_t d;
    /**
     * Opaque room-kind tag (blueprint semantics).
     */
    uint8_t kind;
    /**
     * Apartment index on this floor (`255` = outside every unit).
     */
    uint8_t unit;
    /**
     * Floor area in tiles.
     */
    uint16_t area;
} UrbixRoom;

/**
 * An owned room list handed to foreign code.
 *
 * `data` points at `count` packed [`UrbixRoom`] records in deterministic
 * (row-major scan) order. The caller owns the buffer and must release it
 * with [`urbix_interior_rooms_free`]. Unbuilt cells and null engines yield
 * `{null, 0}`.
 */
typedef struct UrbixRoomList {
    /**
     * Start of the record array; null when empty.
     */
    struct UrbixRoom *data;
    /**
     * Number of records.
     */
    uint64_t count;
} UrbixRoomList;

/**
 * A blended zone-affinity vector, one weight per [`crate::zones::ZoneType`].
 */
typedef struct UrbixZoneAffinity {
    /**
     * Per-zone weights summing to ~1.0.
     */
    float weights[ZONE_COUNT];
} UrbixZoneAffinity;

/**
 * One room template within a zone's [`Blueprint`].
 *
 * A plain data record so room tables are artist-tunable via `WorldConfig`.
 * `kind` is an arbitrary tag the consumer maps to a rendered room (e.g. 0 =
 * living, 1 = kitchen, 2 = bedroom, 3 = office, ...); the engine only treats
 * non-circulation room tiles as `Room` and stores this tag alongside the tile
 * grid for the consumer to interpret.
 */
typedef struct BlueprintRoom {
    /**
     * Opaque room-kind tag (semantics belong to the consumer / renderer).
     */
    uint8_t kind;
    /**
     * Relative selection weight when rolling a room for this zone.
     */
    float weight;
    /**
     * Minimum room grid width in tiles (inclusive).
     */
    uint8_t min_w;
    /**
     * Maximum room grid width in tiles (inclusive).
     */
    uint8_t max_w;
    /**
     * Minimum room grid depth in tiles (inclusive).
     */
    uint8_t min_d;
    /**
     * Maximum room grid depth in tiles (inclusive).
     */
    uint8_t max_d;
    /**
     * Minimum placements per floor (enforced after fill rolls).
     * Serde-defaulted so pre-M14 files parse.
     */
    uint8_t min_count;
    /**
     * Adjacency/program tag bits (`TAG_*`); 0 = no preference.
     * Serde-defaulted so pre-M14 files parse.
     */
    uint8_t tags;
    /**
     * Doors punched per room (`0` means 1). Serde-defaulted.
     */
    uint8_t doors;
} BlueprintRoom;

/**
 * The per-zone rule table driving interior layout for that zone.
 *
 * Mirrors [`crate::zones::ZoneParams`] for interior generation: plain,
 * `#[repr(C)]`, `Serialize`/`Deserialize` data loaded from `WorldConfig`
 * (TOML/JSON) so artists tune interiors without new code. `Default` per zone
 * gives a sensible starting table ([`blueprint_defaults`]).
 *
 * The engine treats these as *rules* — the follow-on `layout` algorithm reads
 * them to carve rooms. The current milestone uses them to drive a
 * deterministic baseline grid: the core placement and the default room tag.
 */
typedef struct Blueprint {
    /**
     * Structural margin: ring of `Wall` tiles around each floor grid.
     */
    uint8_t margin;
    /**
     * Width of the vertical-circulation core (stairs/elevator) in tiles.
     */
    uint8_t core_size;
    /**
     * Number of live entries in `rooms` (`0..=MAX_BLUEPRINT_ROOMS`).
     */
    uint8_t room_count;
    /**
     * Room templates weighted for this zone; only `room_count` are live.
     */
    struct BlueprintRoom rooms[MAX_BLUEPRINT_ROOMS];
    /**
     * Typical floors generate once and clone (`0`) vs re-roll per storey
     * (nonzero). Serde-defaulted so pre-M13 files parse.
     */
    uint8_t vary_typical;
    /**
     * Circulation core wanders per floor (nonzero) vs stacks vertically
     * (`0`, the default). Serde-defaulted so pre-M13 files parse.
     */
    uint8_t wandering_core;
    /**
     * Max apartment/office units per floor (`0` = open plan, no subdivision).
     * Serde-defaulted so pre-M14 files parse.
     */
    uint8_t unit_max;
    /**
     * Plumbing shaft columns per building (`0` = off; capped at 4).
     * WET-tagged rooms snap to these columns on every floor.
     * Serde-defaulted so pre-M14 files parse.
     */
    uint8_t wet_shafts;
    /**
     * Ground-floor blueprint override as a `ZoneType` index
     * (`255` = none): when set, floor 0 uses that zone's blueprint
     * (mixed-use base, e.g. retail under housing).
     * Serde-defaulted so pre-M14 files parse.
     */
    uint8_t ground_zone;
    /**
     * Corridor policy: `0` = double-loaded fill (rooms both sides),
     * `1` = single-loaded (rooms north of a south corridor band).
     * Serde-defaulted so pre-M14 files parse.
     */
    uint8_t corridor;
    /**
     * Second-furniture-piece probability in percent (`0–100`): every room
     * always stamps its primary piece when it fits; the secondary piece
     * rolls against this density. Serde-defaulted so pre-M15 files parse.
     */
    uint8_t furn_density;
} Blueprint;

/**
 * A `#[repr(C)]` snapshot of every tunable that shapes world generation.
 *
 * The struct holds only plain integer/float data so it is trivially
 * FFI-safe and can be passed by pointer to and from C. Construct it with
 * [`WorldConfig::default`] and override the fields you care about, or build
 * a fresh one via `..Default::default()`. For file-based tuning, use
 * [`WorldConfig::from_file`] (TOML or JSON).
 *
 * ## Example
 *
 * ```
 * use urbix::config::WorldConfig;
 *
 * let cfg = WorldConfig {
 *     seed: 445566,
 *     ..Default::default()
 * };
 * assert_eq!(cfg.seed, 445566);
 * assert!(cfg.is_valid());
 * ```
 */

typedef struct ZoneParams {
  float height_min;
  float height_max;
  float density;
  uint8_t block_size;
  uint8_t palette_count;
  uint8_t arterial_every;
  uint8_t slenderness_max;
} ZoneParams;
typedef struct WorldConfig {
    /**
     * World seed; the same seed always yields the same city.
     */
    uint64_t seed;
    /**
     * Cells per chunk side. Must be > 0; defaults to 32.
     */
    uint16_t chunk_size;
    /**
     * Chunk Chebyshev radius kept in cache before eviction. Must be > 0.
     */
    uint32_t draw_distance;
    /**
     * Number of district sites in the Voronoi map. Typically 24–48.
     */
    uint16_t voronoi_site_count;
    /**
     * Half-extent of Voronoi site distribution ([-span, span]²). Default 10_000.
     */
    double voronoi_span;
    /**
     * Shepard exponent `p` in `1/d^p`. Default 4.0.
     */
    double shepard_power;
    /**
     * Shepard epsilon guard for `d=0`. Default 1e-8.
     */
    double shepard_epsilon;
    /**
     * Weighted frequency for tagging Voronoi sites per zone. Must sum ~1.0.
     */
    double zone_weights[ZONE_COUNT];
    /**
     * Per-zone parameters (height, density, block, palette).
     */
    ZoneParams zones[ZONE_COUNT];
    /**
     * Per-zone RGB hues for visualization (promoted from viz).
     */
    uint8_t zone_hues[ZONE_COUNT][3];
    /**
     * Interior room width range [min, max] (inclusive, 6..14 default).
     */
    uint16_t interior_width_range[2];
    /**
     * Interior room height range [min, max] (inclusive, 6..14 default).
     */
    uint16_t interior_height_range[2];
    /**
     * World units per storey: converts building height to floor count.
     */
    float interior_floor_height;
    /**
     * Maximum number of interior floors when deriving from height.
     */
    uint8_t interior_max_floors;
    /**
     * Per-zone interior layout rule tables (Milestone 9 blueprint schema).
     */
    struct Blueprint interior_blueprints[ZONE_COUNT];
} WorldConfig;

/**
 * Header of a chunk buffer, matching the C reference layout.
 */
typedef struct UrbixChunkHeader {
    /**
     * Chunk column index.
     */
    int32_t cx;
    /**
     * Chunk row index.
     */
    int32_t cy;
    /**
     * Total number of cells (`chunk_size × chunk_size`).
     */
    uint32_t cell_count;
    /**
     * Cells per chunk side (e.g. 32).
     */
    uint16_t chunk_size;
    /**
     * Padding to align `seed` on an 8-byte boundary.
     */
    uint8_t _pad[6];
    /**
     * World seed, kept for verification by the consumer.
     */
    uint64_t seed;
} UrbixChunkHeader;

/**
 * Bit flags describing per-cell traits.
 *
 * Implemented as a small manual bitfield to avoid extra dependencies while
 * staying `#[repr(C)]`-friendly. A `CellFlags` value is opaque bits; use the
 * `IS_*` constants and the `contains`/setters to read and write it.
 */
typedef uint8_t CellFlags;
/**
 * Empty set of flags.
 */
#define CellFlags_NONE 0
/**
 * The cell is a street (height is 0 and no building is placed).
 */
#define CellFlags_IS_STREET (1 << 0)
/**
 * The cell is park/green (foliage or open ground).
 */
#define CellFlags_IS_PARK (1 << 1)
/**
 * The cell is an arterial avenue: a wide (2-cell) street on the
 * per-zone `arterial_every` lattice. Always combined with `IS_STREET`
 * so old consumers still render it as a road.
 */
#define CellFlags_IS_ARTERIAL (1 << 2)
/**
 * The cell is a pedestrian plaza: no-build, walkable, height 0.
 * Combined with `IS_STREET` so old renderers draw it as paved ground.
 */
#define CellFlags_IS_PLAZA (1 << 3)
/**
 * The cell is a sidewalk apron: the 1-cell ring inside the street edge.
 * No-build, height 0; renderers draw curb/pavement, not asphalt.
 */
#define CellFlags_IS_SIDEWALK (1 << 4)
/**
 * The cell is a greenway: a dropped street segment reborn as a linear
 * park. No-build, height 0; renderers draw green, like `IS_PARK`.
 */
#define CellFlags_IS_GREENWAY (1 << 5)

/**
 * Deterministic id of a built lot's future interior.
 *
 * Derived from the cell's coordinates, seed, and zone via [`crate::hash`], so
 * a given doorway always leads to the same room across visits. `0` means
 * "no interior" (street, park, or open cell).
 */
typedef uint64_t InteriorId;

/**
 * A single city cell in `#[repr(C)]` layout, one per grid point.
 *
 * Field order and padding match the C reference exactly so the struct can be
 * written straight to the wire and read by foreign consumers. See
 * `Urbix_Project.md` §2.3.
 */
typedef struct UrbixCell {
    /**
     * Building height in world units; `0` for street/open cells.
     */
    float height;
    /**
     * Zone-affinity weight per [`crate::zones::ZoneType`], length 5.
     */
    float zone_affinity[ZONE_COUNT];
    /**
     * Facade color-palette index within the owning zone.
     */
    uint8_t palette_id;
    /**
     * Trait flags (see [`CellFlags`]).
     */
    CellFlags flags;
    /**
     * Explicit 8-byte-alignment padding to match the C layout.
     */
    uint16_t _pad;
    /**
     * Deterministic interior key; `0` when the cell has no interior.
     */
    InteriorId interior_id;
} UrbixCell;

/**
 * Default hues used by `examples/viz.rs` / `interactive.rs` (promoted to config
 * in Milestone 8 so artists tune without recompiling).
 */
#define DEFAULT_ZONE_HUES { { 100, 150, 220, }, { 96, 180, 90, }, { 235, 160, 70, }, { 150, 130, 115, }, { 140, 205, 120, }, }

/**
 * Construct an engine with the given seed and default configuration.
 *
 * Returns an opaque handle the caller owns and must release with
 * [`urbix_engine_destroy`]. Returns a null pointer on allocation failure.
 */
struct UrbixEngine *urbix_engine_create(uint64_t seed);

/**
 * Destroy an engine previously created with [`urbix_engine_create`].
 *
 * A null pointer is a no-op. After this call the handle is dangling and must
 * not be used.
 */
void urbix_engine_destroy(struct UrbixEngine *engine);

/**
 * Generate (or fetch from cache) the chunk at `(cx, cy)`.
 *
 * On success returns an owned [`UrbixChunkBuffer`] with `len == 0` on failure,
 * and `data == null`. The caller must release a successful buffer with
 * [`urbix_chunk_free`].
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
struct UrbixChunkBuffer urbix_generate_chunk(struct UrbixEngine *engine, int32_t cx, int32_t cy);

/**
 * Release a chunk buffer returned by [`urbix_generate_chunk`].
 *
 * ## Safety
 *
 * `buf` must be an *unreleased* buffer from [`urbix_generate_chunk`]. Calling
 * this twice on the same buffer (or with an unrelated buffer) is
 * double-free / undefined behaviour.
 */
void urbix_chunk_free(struct UrbixChunkBuffer buf);

/**
 * Generate the interior layout for the built cell at world space `(wx, wz)`.
 *
 * The engine locates the cell's chunk from the coordinates alone (world space
 * is the canonical interior key — see [`crate::chunk::interior_context_for`]),
 * generates it if needed, and derives the layout from the same path the Rust
 * APIs use, so C consumers and Rust consumers always agree. Requires a built
 * cell (`height > 0`); otherwise the returned header is zeroed.
 *
 * On success returns an owned [`UrbixInterior`]; release it with
 * [`urbix_interior_free`].
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
struct UrbixInterior urbix_generate_interior(struct UrbixEngine *engine, int32_t wx, int32_t wz);

/**
 * Release an interior buffer returned by [`urbix_generate_interior`].
 *
 * ## Safety
 *
 * `interior` must be an *unreleased* result from [`urbix_generate_interior`].
 * Calling this twice on the same buffer (or with an unrelated buffer) is
 * double-free / undefined behaviour.
 */
void urbix_interior_free(struct UrbixInterior interior);

/**
 * Enumerate every room of the built cell at world space `(wx, wz)`.
 *
 * Same lookup path as [`urbix_generate_interior`] (chunk → context →
 * layout, through the engine interior cache), then one [`UrbixRoom`] per
 * 4-connected room component per floor, with apartment and area attached.
 * Release the result with [`urbix_interior_rooms_free`].
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
struct UrbixRoomList urbix_generate_interior_rooms(struct UrbixEngine *engine,
                                                   int32_t wx,
                                                   int32_t wz);

/**
 * Release a room list returned by [`urbix_generate_interior_rooms`].
 *
 * ## Safety
 *
 * `list` must be an *unreleased* result from
 * [`urbix_generate_interior_rooms`]. Calling this twice on the same list
 * (or with an unrelated list) is double-free / undefined behaviour.
 */
void urbix_interior_rooms_free(struct UrbixRoomList list);

/**
 * Query the continuous zone-affinity vector at world coordinates.
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
struct UrbixZoneAffinity urbix_get_zone(struct UrbixEngine *engine, double wx, double wz);

/**
 * Set the draw distance (in chunk Chebyshev units).
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
void urbix_set_draw_distance(struct UrbixEngine *engine, uint32_t radius);

/**
 * Set the cells-per-side chunk size for subsequent generation.
 *
 * Existing cached chunks are cleared (they were built at the old size).
 * Passing `0` is a no-op rather than a panic, since the C boundary must not
 * unwind into the caller.
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
void urbix_set_chunk_size(struct UrbixEngine *engine, uint16_t size);

/**
 * Construct an engine from a fully-specified [`WorldConfig`].
 *
 * Returns null if `config` is null or `!config.is_valid()`.
 *
 * ## Safety
 *
 * `config` must be a valid pointer to a `WorldConfig`, or null.
 */
struct UrbixEngine *urbix_engine_create_with_config(const struct WorldConfig *config);

/**
 * Return the engine's default configuration by value.
 *
 * Lets C consumers start from compiled-in defaults and patch only the
 * fields they care about (e.g. per-zone height bands for proportion
 * experiments), then pass the result to
 * [`urbix_engine_create_with_config`] or [`urbix_set_config`]. The returned
 * value always passes [`WorldConfig::is_valid`].
 */
struct WorldConfig urbix_default_config(void);

/**
 * Replace an engine's configuration wholesale (modular customization).
 *
 * Regenerates the Voronoi diagram and clears the chunk cache. No-ops on null
 * handles or invalid configs; never panics across the FFI boundary.
 *
 * ## Safety
 *
 * `engine` must be a valid handle, `config` a valid `WorldConfig` pointer.
 */
void urbix_set_config(struct UrbixEngine *engine, const struct WorldConfig *config);
/* ---- Compatibility shims for old manual header ---- */
#define URBIX_FLAG_STREET CellFlags_IS_STREET
#define URBIX_FLAG_PARK CellFlags_IS_PARK
#define URBIX_FLAG_ARTERIAL CellFlags_IS_ARTERIAL
#define URBIX_FLAG_PLAZA CellFlags_IS_PLAZA
#define URBIX_FLAG_SIDEWALK CellFlags_IS_SIDEWALK
#define URBIX_FLAG_GREENWAY CellFlags_IS_GREENWAY

/* ---- Compile-time layout checks (inside include guard) ---- */
_Static_assert(sizeof(UrbixChunkHeader) == 32, "UrbixChunkHeader must be 32 bytes");
_Static_assert(sizeof(UrbixCell) == 40,      "UrbixCell must be 40 bytes");
_Static_assert(sizeof(UrbixRoom) == 10,      "UrbixRoom must be 10 bytes");
_Static_assert(_Alignof(UrbixChunkHeader) == 8, "UrbixChunkHeader must be 8-byte aligned");
_Static_assert(_Alignof(UrbixCell) == 8,       "UrbixCell must be 8-byte aligned");
#endif  /* URBIX_H */
