/* include/urbix.h — Auto-generated by cbindgen. Do not edit manually;
 * regenerate with `cargo build`.
 *
 * See Urbix_Project.md §2.3 (wire format) and §2.4 (FFI surface). */

#ifndef URBIX_H
#define URBIX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Interior layout blueprint selection (see `layout.rs` / `InteriorContext`).
 */
#define LAYOUT_PICK 40

/**
 * Interior per-floor layout variation (see `layout.rs`).
 */
#define LAYOUT_FLOOR 41

/**
 * Interior room-kind selection (see `layout.rs`).
 */
#define LAYOUT_ROOM 42

/**
 * Interior room size (width/depth) draw (see `layout.rs`).
 */
#define LAYOUT_ROOM_SIZE 43

/**
 * Interior door placement (see `layout.rs`).
 */
#define LAYOUT_DOOR 44

/**
 * Interior furniture slot density (see `layout.rs`).
 */
#define LAYOUT_FURNITURE 45

/**
 * Maximum room templates a single zone [`Blueprint`] can hold.
 *
 * The blueprint is a fixed-size `#[repr(C)]` record so it can live inside
 * `WorldConfig` and cross the FFI; `room_count` marks how many of the
 * `MAX_BLUEPRINT_ROOMS` slots are live. 8 comfortably fits all five zones'
 * defaults (largest is Downtown at 4).
 */
#define MAX_BLUEPRINT_ROOMS 8

/**
 * Number of `InteriorLayout` floors assumed for worlds units per storey when
 * deriving `floor_count` from building height. Kept as a compile-time default;
 * `WorldConfig.interior_floor_height` overrides it at runtime.
 */
#define DEFAULT_FLOOR_HEIGHT 4.0

/**
 * Number of `InteriorLayout` floors cap when deriving `floor_count` from
 * building height. `WorldConfig.interior_max_floors` overrides it at runtime.
 */
#define DEFAULT_MAX_FLOORS 64

/**
 * The number of distinct zone types.
 */
#define ZONE_COUNT 5

/**
 * Opaque handle to a [`WorldEngine`], owned by the caller.
 *
 * Never dereference from foreign code; pass it back to the FFI functions.
 * Deliberately not `#[repr(C)]`: it is a zero-sized opaque marker whose layout
 * is irrelevant, and cbindgen emits an opaque forward-declared typedef for it.
 */
typedef struct UrbixEngine UrbixEngine;

/**
 * An owned chunk's packed bytes handed to foreign code.
 *
 * `data` points at `len` bytes: a [`crate::data::ChunkHeader`] followed by
 * `cell_count` [`crate::data::Cell`] records with no padding. The caller owns
 * this buffer and must free it with [`urbix_chunk_free`].
 */
typedef struct UrbixChunkBuffer {
    /**
     * Start of the wire buffer (header + cells).
     */
    uint8_t *data;
    /**
     * Total byte length (`sizeof(header) + cell_count * sizeof(cell)`).
     */
    uint64_t len;
} UrbixChunkBuffer;

/**
 * A blended zone-affinity vector, one weight per [`crate::zones::ZoneType`].
 */
typedef struct UrbixZoneAffinity {
    /**
     * Per-zone weights summing to ~1.0.
     */
    float weights[ZONE_COUNT];
} UrbixZoneAffinity;

/**
 * One room template within a zone's [`Blueprint`].
 *
 * A plain data record so room tables are artist-tunable via `WorldConfig`.
 * `kind` is an arbitrary tag the consumer maps to a rendered room (e.g. 0 =
 * living, 1 = kitchen, 2 = bedroom, 3 = office, ...); the engine only treats
 * non-circulation room tiles as `Room` and stores this tag alongside the tile
 * grid for the consumer to interpret.
 */
typedef struct BlueprintRoom {
    /**
     * Opaque room-kind tag (semantics belong to the consumer / renderer).
     */
    uint8_t kind;
    /**
     * Relative selection weight when rolling a room for this zone.
     */
    float weight;
    /**
     * Minimum room grid width in tiles (inclusive).
     */
    uint8_t min_w;
    /**
     * Maximum room grid width in tiles (inclusive).
     */
    uint8_t max_w;
    /**
     * Minimum room grid depth in tiles (inclusive).
     */
    uint8_t min_d;
    /**
     * Maximum room grid depth in tiles (inclusive).
     */
    uint8_t max_d;
} BlueprintRoom;

/**
 * The per-zone rule table driving interior layout for that zone.
 *
 * Mirrors [`crate::zones::ZoneParams`] for interior generation: plain,
 * `#[repr(C)]`, `Serialize`/`Deserialize` data loaded from `WorldConfig`
 * (TOML/JSON) so artists tune interiors without new code. `Default` per zone
 * gives a sensible starting table ([`blueprint_defaults`]).
 *
 * The engine treats these as *rules* — the follow-on `layout` algorithm reads
 * them to carve rooms. The current milestone uses them to drive a
 * deterministic baseline grid: the core placement and the default room tag.
 */
typedef struct Blueprint {
    /**
     * Structural margin: ring of `Wall` tiles around each floor grid.
     */
    uint8_t margin;
    /**
     * Width of the vertical-circulation core (stairs/elevator) in tiles.
     */
    uint8_t core_size;
    /**
     * Number of live entries in `rooms` (`0..=MAX_BLUEPRINT_ROOMS`).
     */
    uint8_t room_count;
    /**
     * Room templates weighted for this zone; only `room_count` are live.
     */
    struct BlueprintRoom rooms[MAX_BLUEPRINT_ROOMS];
} Blueprint;

/**
 * A `#[repr(C)]` snapshot of every tunable that shapes world generation.
 *
 * The struct holds only plain integer/float data so it is trivially
 * FFI-safe and can be passed by pointer to and from C. Construct it with
 * [`WorldConfig::default`] and override the fields you care about, or build
 * a fresh one via `..Default::default()`. For file-based tuning, use
 * [`WorldConfig::from_file`] (TOML or JSON).
 *
 * ## Example
 *
 * ```
 * use urbix::config::WorldConfig;
 *
 * let cfg = WorldConfig {
 *     seed: 445566,
 *     ..Default::default()
 * };
 * assert_eq!(cfg.seed, 445566);
 * assert!(cfg.is_valid());
 * ```
 */

typedef struct ZoneParams {
  float height_min;
  float height_max;
  float density;
  uint8_t block_size;
  uint8_t palette_count;
} ZoneParams;
typedef struct WorldConfig {
    /**
     * World seed; the same seed always yields the same city.
     */
    uint64_t seed;
    /**
     * Cells per chunk side. Must be > 0; defaults to 32.
     */
    uint16_t chunk_size;
    /**
     * Chunk Chebyshev radius kept in cache before eviction. Must be > 0.
     */
    uint32_t draw_distance;
    /**
     * Number of district sites in the Voronoi map. Typically 24–48.
     */
    uint16_t voronoi_site_count;
    /**
     * Half-extent of Voronoi site distribution ([-span, span]²). Default 10_000.
     */
    double voronoi_span;
    /**
     * Shepard exponent `p` in `1/d^p`. Default 4.0.
     */
    double shepard_power;
    /**
     * Shepard epsilon guard for `d=0`. Default 1e-8.
     */
    double shepard_epsilon;
    /**
     * Weighted frequency for tagging Voronoi sites per zone. Must sum ~1.0.
     */
    double zone_weights[ZONE_COUNT];
    /**
     * Per-zone parameters (height, density, block, palette).
     */
    ZoneParams zones[ZONE_COUNT];
    /**
     * Per-zone RGB hues for visualization (promoted from viz).
     */
    uint8_t zone_hues[ZONE_COUNT][3];
    /**
     * Interior room width range [min, max] (inclusive, 6..14 default).
     */
    uint16_t interior_width_range[2];
    /**
     * Interior room height range [min, max] (inclusive, 6..14 default).
     */
    uint16_t interior_height_range[2];
    /**
     * World units per storey: converts building height to floor count.
     */
    float interior_floor_height;
    /**
     * Maximum number of interior floors when deriving from height.
     */
    uint8_t interior_max_floors;
    /**
     * Per-zone interior layout rule tables (Milestone 9 blueprint schema).
     */
    struct Blueprint interior_blueprints[ZONE_COUNT];
} WorldConfig;

/**
 * Header of a chunk buffer, matching the C reference layout.
 */
typedef struct UrbixChunkHeader {
    /**
     * Chunk column index.
     */
    int32_t cx;
    /**
     * Chunk row index.
     */
    int32_t cy;
    /**
     * Total number of cells (`chunk_size × chunk_size`).
     */
    uint32_t cell_count;
    /**
     * Cells per chunk side (e.g. 32).
     */
    uint16_t chunk_size;
    /**
     * Padding to align `seed` on an 8-byte boundary.
     */
    uint8_t _pad[6];
    /**
     * World seed, kept for verification by the consumer.
     */
    uint64_t seed;
} UrbixChunkHeader;

/**
 * Bit flags describing per-cell traits.
 *
 * Implemented as a small manual bitfield to avoid extra dependencies while
 * staying `#[repr(C)]`-friendly. A `CellFlags` value is opaque bits; use the
 * `IS_*` constants and the `contains`/setters to read and write it.
 */
typedef uint8_t CellFlags;
/**
 * Empty set of flags.
 */
#define CellFlags_NONE 0
/**
 * The cell is a street (height is 0 and no building is placed).
 */
#define CellFlags_IS_STREET (1 << 0)
/**
 * The cell is park/green (foliage or open ground).
 */
#define CellFlags_IS_PARK (1 << 1)

/**
 * Deterministic id of a built lot's future interior.
 *
 * Derived from the cell's coordinates, seed, and zone via [`crate::hash`], so
 * a given doorway always leads to the same room across visits. `0` means
 * "no interior" (street, park, or open cell).
 */
typedef uint64_t InteriorId;

/**
 * A single city cell in `#[repr(C)]` layout, one per grid point.
 *
 * Field order and padding match the C reference exactly so the struct can be
 * written straight to the wire and read by foreign consumers. See
 * `Urbix_Project.md` §2.3.
 */
typedef struct UrbixCell {
    /**
     * Building height in world units; `0` for street/open cells.
     */
    float height;
    /**
     * Zone-affinity weight per [`crate::zones::ZoneType`], length 5.
     */
    float zone_affinity[ZONE_COUNT];
    /**
     * Facade color-palette index within the owning zone.
     */
    uint8_t palette_id;
    /**
     * Trait flags (see [`CellFlags`]).
     */
    CellFlags flags;
    /**
     * Explicit 8-byte-alignment padding to match the C layout.
     */
    uint16_t _pad;
    /**
     * Deterministic interior key; `0` when the cell has no interior.
     */
    InteriorId interior_id;
} UrbixCell;

/**
 * Default hues used by `examples/viz.rs` / `interactive.rs` (promoted to config
 * in Milestone 8 so artists tune without recompiling).
 */
#define DEFAULT_ZONE_HUES { { 100, 150, 220, }, { 96, 180, 90, }, { 235, 160, 70, }, { 150, 130, 115, }, { 140, 205, 120, }, }

/**
 * Construct an engine with the given seed and default configuration.
 *
 * Returns an opaque handle the caller owns and must release with
 * [`urbix_engine_destroy`]. Returns a null pointer on allocation failure.
 */
struct UrbixEngine *urbix_engine_create(uint64_t seed);

/**
 * Destroy an engine previously created with [`urbix_engine_create`].
 *
 * A null pointer is a no-op. After this call the handle is dangling and must
 * not be used.
 */
void urbix_engine_destroy(struct UrbixEngine *engine);

/**
 * Generate (or fetch from cache) the chunk at `(cx, cy)`.
 *
 * On success returns an owned [`UrbixChunkBuffer`] with `len == 0` on failure,
 * and `data == null`. The caller must release a successful buffer with
 * [`urbix_chunk_free`].
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
struct UrbixChunkBuffer urbix_generate_chunk(struct UrbixEngine *engine, int32_t cx, int32_t cy);

/**
 * Release a chunk buffer returned by [`urbix_generate_chunk`].
 *
 * ## Safety
 *
 * `buf` must be an *unreleased* buffer from [`urbix_generate_chunk`]. Calling
 * this twice on the same buffer (or with an unrelated buffer) is
 * double-free / undefined behaviour.
 */
void urbix_chunk_free(struct UrbixChunkBuffer buf);

/**
 * Query the continuous zone-affinity vector at world coordinates.
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
struct UrbixZoneAffinity urbix_get_zone(struct UrbixEngine *engine, double wx, double wz);

/**
 * Set the draw distance (in chunk Chebyshev units).
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
void urbix_set_draw_distance(struct UrbixEngine *engine, uint32_t radius);

/**
 * Set the cells-per-side chunk size for subsequent generation.
 *
 * Existing cached chunks are cleared (they were built at the old size).
 * Passing `0` is a no-op rather than a panic, since the C boundary must not
 * unwind into the caller.
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
void urbix_set_chunk_size(struct UrbixEngine *engine, uint16_t size);

/**
 * Construct an engine from a fully-specified [`WorldConfig`].
 *
 * Returns null if `config` is null or `!config.is_valid()`.
 *
 * ## Safety
 *
 * `config` must be a valid pointer to a `WorldConfig`, or null.
 */
struct UrbixEngine *urbix_engine_create_with_config(const struct WorldConfig *config);

/**
 * Replace an engine's configuration wholesale (modular customization).
 *
 * Regenerates the Voronoi diagram and clears the chunk cache. No-ops on null
 * handles or invalid configs; never panics across the FFI boundary.
 *
 * ## Safety
 *
 * `engine` must be a valid handle, `config` a valid `WorldConfig` pointer.
 */
void urbix_set_config(struct UrbixEngine *engine, const struct WorldConfig *config);
/* ---- Compatibility shims for old manual header ---- */
#define URBIX_FLAG_STREET CellFlags_IS_STREET
#define URBIX_FLAG_PARK CellFlags_IS_PARK

/* ---- Compile-time layout checks (inside include guard) ---- */
_Static_assert(sizeof(UrbixChunkHeader) == 32, "UrbixChunkHeader must be 32 bytes");
_Static_assert(sizeof(UrbixCell) == 40,      "UrbixCell must be 40 bytes");
_Static_assert(_Alignof(UrbixChunkHeader) == 8, "UrbixChunkHeader must be 8-byte aligned");
_Static_assert(_Alignof(UrbixCell) == 8,       "UrbixCell must be 8-byte aligned");
#endif  /* URBIX_H */
