/* include/urbix.h — Auto-generated by cbindgen. Do not edit manually;
 * regenerate with `cargo build`.
 *
 * See Urbix_Project.md §2.3 (wire format) and §2.4 (FFI surface). */

#ifndef URBIX_H
#define URBIX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The number of distinct zone types.
 */
#define ZONE_COUNT 5

/**
 * Opaque handle to a [`WorldEngine`], owned by the caller.
 *
 * Never dereference from foreign code; pass it back to the FFI functions.
 * Deliberately not `#[repr(C)]`: it is a zero-sized opaque marker whose layout
 * is irrelevant, and cbindgen emits an opaque forward-declared typedef for it.
 */
typedef struct UrbixEngine UrbixEngine;

/**
 * An owned chunk's packed bytes handed to foreign code.
 *
 * `data` points at `len` bytes: a [`crate::data::ChunkHeader`] followed by
 * `cell_count` [`crate::data::Cell`] records with no padding. The caller owns
 * this buffer and must free it with [`urbix_chunk_free`].
 */
typedef struct UrbixChunkBuffer {
    /**
     * Start of the wire buffer (header + cells).
     */
    uint8_t *data;
    /**
     * Total byte length (`sizeof(header) + cell_count * sizeof(cell)`).
     */
    uint64_t len;
} UrbixChunkBuffer;

/**
 * A blended zone-affinity vector, one weight per [`crate::zones::ZoneType`].
 */
typedef struct UrbixZoneAffinity {
    /**
     * Per-zone weights summing to ~1.0.
     */
    float weights[ZONE_COUNT];
} UrbixZoneAffinity;

/**
 * Header of a chunk buffer, matching the C reference layout.
 */
typedef struct UrbixChunkHeader {
    /**
     * Chunk column index.
     */
    int32_t cx;
    /**
     * Chunk row index.
     */
    int32_t cy;
    /**
     * Total number of cells (`chunk_size × chunk_size`).
     */
    uint32_t cell_count;
    /**
     * Cells per chunk side (e.g. 32).
     */
    uint16_t chunk_size;
    /**
     * Padding to align `seed` on an 8-byte boundary.
     */
    uint8_t _pad[6];
    /**
     * World seed, kept for verification by the consumer.
     */
    uint64_t seed;
} UrbixChunkHeader;

/**
 * Bit flags describing per-cell traits.
 *
 * Implemented as a small manual bitfield to avoid extra dependencies while
 * staying `#[repr(C)]`-friendly. A `CellFlags` value is opaque bits; use the
 * `IS_*` constants and the `contains`/setters to read and write it.
 */
typedef uint8_t CellFlags;
/**
 * Empty set of flags.
 */
#define CellFlags_NONE 0
/**
 * The cell is a street (height is 0 and no building is placed).
 */
#define CellFlags_IS_STREET (1 << 0)
/**
 * The cell is park/green (foliage or open ground).
 */
#define CellFlags_IS_PARK (1 << 1)

/**
 * Deterministic id of a built lot's future interior.
 *
 * Derived from the cell's coordinates, seed, and zone via [`crate::hash`], so
 * a given doorway always leads to the same room across visits. `0` means
 * "no interior" (street, park, or open cell).
 */
typedef uint64_t InteriorId;

/**
 * A single city cell in `#[repr(C)]` layout, one per grid point.
 *
 * Field order and padding match the C reference exactly so the struct can be
 * written straight to the wire and read by foreign consumers. See
 * `Urbix_Project.md` §2.3.
 */
typedef struct UrbixCell {
    /**
     * Building height in world units; `0` for street/open cells.
     */
    float height;
    /**
     * Zone-affinity weight per [`crate::zones::ZoneType`], length 5.
     */
    float zone_affinity[ZONE_COUNT];
    /**
     * Facade color-palette index within the owning zone.
     */
    uint8_t palette_id;
    /**
     * Trait flags (see [`CellFlags`]).
     */
    CellFlags flags;
    /**
     * Explicit 8-byte-alignment padding to match the C layout.
     */
    uint16_t _pad;
    /**
     * Deterministic interior key; `0` when the cell has no interior.
     */
    InteriorId interior_id;
} UrbixCell;

/**
 * Construct an engine with the given seed and default configuration.
 *
 * Returns an opaque handle the caller owns and must release with
 * [`urbix_engine_destroy`]. Returns a null pointer on allocation failure.
 */
struct UrbixEngine *urbix_engine_create(uint64_t seed);

/**
 * Destroy an engine previously created with [`urbix_engine_create`].
 *
 * A null pointer is a no-op. After this call the handle is dangling and must
 * not be used.
 */
void urbix_engine_destroy(struct UrbixEngine *engine);

/**
 * Generate (or fetch from cache) the chunk at `(cx, cy)`.
 *
 * On success returns an owned [`UrbixChunkBuffer`] with `len == 0` on failure,
 * and `data == null`. The caller must release a successful buffer with
 * [`urbix_chunk_free`].
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
struct UrbixChunkBuffer urbix_generate_chunk(struct UrbixEngine *engine, int32_t cx, int32_t cy);

/**
 * Release a chunk buffer returned by [`urbix_generate_chunk`].
 *
 * ## Safety
 *
 * `buf` must be an *unreleased* buffer from [`urbix_generate_chunk`]. Calling
 * this twice on the same buffer (or with an unrelated buffer) is
 * double-free / undefined behaviour.
 */
void urbix_chunk_free(struct UrbixChunkBuffer buf);

/**
 * Query the continuous zone-affinity vector at world coordinates.
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
struct UrbixZoneAffinity urbix_get_zone(struct UrbixEngine *engine, double wx, double wz);

/**
 * Set the draw distance (in chunk Chebyshev units).
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
void urbix_set_draw_distance(struct UrbixEngine *engine, uint32_t radius);

/**
 * Set the cells-per-side chunk size for subsequent generation.
 *
 * Existing cached chunks are cleared (they were built at the old size).
 * Passing `0` is a no-op rather than a panic, since the C boundary must not
 * unwind into the caller.
 *
 * ## Safety
 *
 * `engine` must be a valid, non-null handle from [`urbix_engine_create`].
 */
void urbix_set_chunk_size(struct UrbixEngine *engine, uint16_t size);

#endif  /* URBIX_H */

/* ---- Compile-time layout checks ---------------------------------------- */
_Static_assert(sizeof(UrbixChunkHeader) == 32, "UrbixChunkHeader must be 32 bytes");
_Static_assert(sizeof(UrbixCell) == 40,      "UrbixCell must be 40 bytes");
_Static_assert(_Alignof(UrbixChunkHeader) == 8, "UrbixChunkHeader must be 8-byte aligned");
_Static_assert(_Alignof(UrbixCell) == 8,       "UrbixCell must be 8-byte aligned");
